### ISSUE TITLE
Chartmuseum should have it's helm chart

### ISSUE THREAD

**Issue by davidovich** [chartmuseum/chartmuseum#1]
This would allow easy installation in a kubernetes cluster.

**Comment by jdolitsky** [comment]
@davidovich you can find the chartmuseum chart in the official kubernetes incubator: https://github.com/kubernetes/charts/tree/master/incubator/chartmuseum

Also on KubeApps:
https://kubeapps.com/charts/incubator/chartmuseum

Keep in mind that it's currently missing a lot in terms of storage options. For now, it's just using an emptyDir volume, which should stick around as long as the pod. If you get it working with persistent or cloud storage, please submit a PR to the kubernetes/charts repo. Thanks!

**Comment by davidovich** [comment]
Thank you, my colleague @cjauvin will be implementing this PR soon.
