### ISSUE TITLE
Add Prometheus metrics

### ISSUE THREAD

**Issue by cjauvin** [chartmuseum/chartmuseum#11]
Hi Josh,

I have another request which stems from a requirement in the business context where we'll use ChartMuseum (but would also make sense in a more general context I believe): add Prometheus metrics, using https://github.com/prometheus/client_golang.

Things it would be nice to (optionally) measure:

* Number of requests, by type
* Duration of requests
* Number of charts served
* Time it takes to regenerate index
* Etc.

What do you think? Of course if you agree once more, I'll be happy to propose an implementation.

**Comment by jdolitsky** [comment]
@cjauvin Yes, I think this would be very helpful. Please share the details of implementation
