### ISSUE TITLE
Unable to start docker image

### ISSUE THREAD

**Issue by trobert2** [chartmuseum/chartmuseum#2]
I believe that more details about how the tool woks is needed:
 [1] What is the basic set of IAM permissions needed to work with this? 
 [1] Will the tool work with aws profiles (as per the existing example mounting `~/.aws` in the docker image)
 [1] How is the bucket accessed? Is the data replicated and then served?

Example that didn't work for me, but worked for calling the API:
policy attached to the assumed role:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:Get*",
                "s3:List*"
            ],
            "Resource": "arn:aws:s3:::*"
        }
    ]
}
```

`~/.aws/config` contains:

```
[profile default]
role_arn = arn:aws:iam::00redacted000:role/ReadCharts
source_profile = default
```

`~/.aws/credentials` contains the standard credentials set.

commad used: `docker run -p 8080:8080 -v ~/.aws:/root/.aws:ro chartmuseum/chartmuseum:latest --debug --port=8080  --storage="amazon" --storage-amazon-bucket="mycompany-helmcharts" --storage-amazon-prefix="" --storage-amazon-region="eu-central-1"`

error:

```
2017-10-05T09:45:33.255Z	DEBUG	chartmuseum/server.go:166	Acquiring storage cache lock
2017-10-05T09:45:33.255Z	DEBUG	chartmuseum/server.go:168	Storage cache lock acquired
2017-10-05T09:45:33.613Z	DEBUG	chartmuseum/server.go:170	Releasing storage cache lock
AccessDenied: Access Denied
	status code: 403, request id: CxxxxredactedxxxxBA, host id: c1EDzxxxxxxxredactedxxxxxxx7X+e0xxxxxxxxxRlMl8=
```

**Comment by jdolitsky** [comment]
Hi, I'm not sure best way to assist with this. Get/List should be enough if you're only using this for GET requests, otherwise you will need write permissions as well.

Can you please try running the binary and see if you get the same result locally? You can also try replacing the -v ~/.aws:/root/.aws:ro with -e AWS_ACCESS_KEY_ID=xxx and -e AWS_SECRET_ACCESS_KEY=xxx and see how that works

**Comment by jdolitsky** [comment]
@trobert2 can you please make sure your credentials are working with the following
```bash
docker run --rm \
  -v ~/.aws:/root/.aws:ro \
  --entrypoint sh \
  chartmuseum/chartmuseum:latest \
  -c 'apk add --update py-pip &&
      pip install awscli &&
      aws s3 ls mycompany-helmcharts --region=eu-central-1'
```

**Comment by trobert2** [comment]
@jdolitsky as specified the credentials and the roles in the profile have been tested with listing/getting objects in that bucket. I think the best way to help the users would be to improve the documentation.

Running the command that you suggested tells me that there aren't write permissions in the attached `.aws` volume

```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.6/community/x86_64/APKINDEX.tar.gz
(1/12) Installing libbz2 (1.0.6-r5)
(2/12) Installing expat (2.2.0-r1)
(3/12) Installing libffi (3.2.1-r3)
(4/12) Installing gdbm (1.12-r0)
(5/12) Installing ncurses-terminfo-base (6.0-r8)
(6/12) Installing ncurses-terminfo (6.0-r8)
(7/12) Installing ncurses-libs (6.0-r8)
(8/12) Installing readline (6.3.008-r5)
(9/12) Installing sqlite-libs (3.20.1-r0)
(10/12) Installing python2 (2.7.13-r1)
(11/12) Installing py-setuptools (33.1.1-r1)
(12/12) Installing py2-pip (9.0.1-r1)
Executing busybox-1.26.2-r5.trigger
OK: 62 MiB in 24 packages
Collecting awscli
  Downloading awscli-1.11.166-py2.py3-none-any.whl (1.2MB)
Collecting botocore==1.7.24 (from awscli)
  Downloading botocore-1.7.24-py2.py3-none-any.whl (3.7MB)
Collecting docutils>=0.10 (from awscli)
  Downloading docutils-0.14-py2-none-any.whl (543kB)
Collecting colorama<=0.3.7,>=0.2.5 (from awscli)
  Downloading colorama-0.3.7-py2.py3-none-any.whl
Collecting PyYAML<=3.12,>=3.10 (from awscli)
  Downloading PyYAML-3.12.tar.gz (253kB)
Collecting rsa<=3.5.0,>=3.1.2 (from awscli)
  Downloading rsa-3.4.2-py2.py3-none-any.whl (46kB)
Collecting s3transfer<0.2.0,>=0.1.9 (from awscli)
  Downloading s3transfer-0.1.11-py2.py3-none-any.whl (54kB)
Collecting python-dateutil<3.0.0,>=2.1 (from botocore==1.7.24->awscli)
  Downloading python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
Collecting jmespath<1.0.0,>=0.7.1 (from botocore==1.7.24->awscli)
  Downloading jmespath-0.9.3-py2.py3-none-any.whl
Collecting pyasn1>=0.1.3 (from rsa<=3.5.0,>=3.1.2->awscli)
  Downloading pyasn1-0.3.7-py2.py3-none-any.whl (63kB)
Collecting futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" (from s3transfer<0.2.0,>=0.1.9->awscli)
  Downloading futures-3.1.1-py2-none-any.whl
Collecting six>=1.5 (from python-dateutil<3.0.0,>=2.1->botocore==1.7.24->awscli)
  Downloading six-1.11.0-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil, jmespath, docutils, botocore, colorama, PyYAML, pyasn1, rsa, futures, s3transfer, awscli
  Running setup.py install for PyYAML: started
    Running setup.py install for PyYAML: finished with status 'done'
Successfully installed PyYAML-3.12 awscli-1.11.166 botocore-1.7.24 colorama-0.3.7 docutils-0.14 futures-3.1.1 jmespath-0.9.3 pyasn1-0.3.7 python-dateutil-2.6.1 rsa-3.4.2 s3transfer-0.1.11 six-1.11.0

[Errno 30] Read-only file system: '/root/.aws/cli'
```

**Comment by trobert2** [comment]
with regards to the suggestion of using `-e AWS_ACCESS_KEY_ID=xxx and -e AWS_SECRET_ACCESS_KEY=xxx`, The user created for this purpose only has permissions to assume role, so the config section would have to be there as per: http://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html

This is the accepted "most secure" way of doing it. We need this to pass auditing in our company. 
**FOR OTHER READERS:** If I could attach the permissions directly to a group that the user would adhere to, this solution could work.

**Comment by jdolitsky** [comment]
@trobert2 can you try this command using an image with built-in awscli?
```bash
docker run --rm \
  -v ~/.aws:/root/.aws:ro \
  xueshanf/awscli:latest \
  aws s3 ls mycompany-helmcharts --region=eu-central-1
```

If that still doesn't work, would you mind trying the first command with the `:ro` removed?

**Comment by trobert2** [comment]
removing the `read only flag` allows me to list the objects in the bucket. Running the initial command with the same condition, yields the same error.

**Comment by jdolitsky** [comment]
hm ok. Can you maybe try to change the policy from
`"Resource": "arn:aws:s3:::*"` to
`"Resource": "arn:aws:s3:::mycompany-helmcharts/*"`
?

**Comment by trobert2** [comment]
No luck. Do you expect any write permissions for doing something with `index.yaml` ?
Is this set-up working for you? can you reproduce it under the same conditions?

**Comment by jdolitsky** [comment]
I'm wondering if it has to do with the permissions on the objects in the bucket.. Are you already storing .tgz files at that location? I'm wondering if you would have same result with `"Action": "s3:*"`

I just tried your original policy and it works for me, in Docker

If you want to message me on kubernetes slack, we can work through this in realtime

**Comment by trobert2** [comment]
attaching the policy to the group that the user belongs to works. I have managed to start the service. I believe the `profiles` are the culprit here, unless there's a PEBKAC somewhere, which I can't see.

This is the policy I used in the end:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:List*"
            ],
            "Resource": "arn:aws:s3:::*"
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "s3:Get*",
                "s3:List*"
            ],
            "Resource": "arn:aws:s3:::mycompany-helmcharts/*"
        }
    ]
}
```

**Comment by jdolitsky** [comment]
Closing this issue as it was related to AWS/environment. Will add more details on necessary AWS policies needed to run this in the near future.

**Comment by qrevel** [comment]
@jdolitsky did you come up with the least privileged IAM policy we need to use for chartmuseum?

**Comment by jdolitsky** [comment]
@qrevel No, unfortunately. Does the above work for you?

**Comment by jdolitsky** [comment]
It also depends on if you will be using the /api routes or not (write access)

**Comment by qrevel** [comment]
I gave full access (`s3:*`) to my helm chart bucket but I'm searching for the least privileged policy.
