### ISSUE TITLE
Add possibility to overwrite chart in repository

### ISSUE THREAD

**Issue by mahnkong** [chartmuseum/chartmuseum#3]
Hi there,

it should be possible to overwrite existing charts served by the museum (i.e. to use PUT for creation and POST for updating a chart resource) - this would be especially useful when serving charts still under development. (similar to the possibility of uploading maven snapshots several times in the Java world)

This feature should be disabled by default and optionally enabled by providing a cmdline option, env var or something similar.

Best regards,
Andreas

**Comment by jdolitsky** [comment]
Hi Andreas, this is not a bad idea. Do you mean POST for create, PUT for update? Can you please describe what this would look like in terms of the API? For example, would the new route be
`PUT /api/charts/<name>/<version>` ?

If you want to achieve this right now, you could do a DELETE then a POST

**Comment by mahnkong** [comment]
Hi, yes exactly something like that was the idea. ( I always mix up POST vs PUT ;) ) In the mean time, I will use the DELETE and POST approach.

**Comment by jdolitsky** [comment]
What are your thoughts on _not_ adding an additional API route, but instead adding a new option `--allow-overwrite` that wouldnt check for the charts existence on POST /api/charts ?

**Comment by mahnkong** [comment]
That idea sound also good to me.

**Comment by jdolitsky** [comment]
@mahnkong The `--allow-overwrite` flag has been added in v0.2.2. Thanks for your suggestion!
