### ISSUE TITLE
Add possibility to post form data

### ISSUE THREAD

**Issue by cjauvin** [chartmuseum/chartmuseum#7]
Hi,

Would you be open to the idea of also supporting form data posts? With it, it would be possible to upload a chart by doing something like:

```
$ curl --form "chartfile=@/path/to/chart.tgz" ...
```

**Comment by jdolitsky** [comment]
Hi, I'm not necessarily opposed. Can you explain the use case? Does the current method of uploading not work for your implementation?

**Comment by cjauvin** [comment]
In our own tooling we had studied the question a while ago and went with `multipart/form-data` because it is apparently more efficient in this context:

https://stackoverflow.com/questions/14063311/curl-post-data-binary-vs-form/26894918#26894918
https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data/4073451#4073451

So given that our tooling is already using this interface, it would be easier for us if chartmuseum (which we are currently in the process of testing as a replacement for our own internally developed chart repo server) also supported it.

If you are interested in the feature, I would gladly implement it and open a PR soon.

**Comment by jdolitsky** [comment]
Ok. I'm totally fine with it so long as both methods are supported. If you want to submit a PR please feel free :)

I'd like to use the name of the route as the form field, i.e. "chart" for POST /api/charts and "prov" for POST /api/prov. Ideally both "chart" and "prov" could be passed to POST /api/charts so we can deprecate POST /api/prov in the future.

If the form field is not found in the request, should fall back to old method of loading the chart from the binary post data.

Adding some tests for this in pkg/chartmuseum/server_test.go would be greatly appreciated as well. We can also add them in later if you're having issues.

Thank you!

**Comment by jdolitsky** [comment]
This feature is in v0.2.1
