### ISSUE TITLE
customizable S3 endpoint

### ISSUE THREAD

**Issue by 1337andre** [chartmuseum/chartmuseum#8]
Hi,

i'd like to use chartmuseum with my own S3 Storage Backend like mini.io.

Would it be possible to make S3 endpoint customizable?

with ruby lib fog-aws this possible: https://github.com/minio/cookbook/blob/master/docs/fog-aws-for-ruby-with-minio.md#3-example 

Could it possible that, the aws lib you use already supports custom endpoints? https://github.com/aws/aws-sdk-go/blob/master/example/aws/endpoints/customEndpoint/customEndpoint.go

greetings
Andre

**Comment by jdolitsky** [comment]
Hi, yes this feature should be fairly easy to add

**Comment by jdolitsky** [comment]
@1337andre There is now a `--storage-amazon-endpoint` flag in v0.2.2. I've tested this with a local Minio install. Please let us know if you have any issues. Thanks!
